# Generated by Django 2.2.5 on 2020-04-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='help_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
