# Generated by Django 2.2.5 on 2020-04-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_reply_help_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='can_uname',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='com_username',
        ),
    ]
