# Generated by Django 2.2.5 on 2020-04-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20200413_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helpdesk',
            old_name='com_username',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='helpdesk',
            name='can_uname',
        ),
    ]
