# Generated by Django 2.2.5 on 2020-04-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20200413_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_amount', models.FloatField()),
                ('reg_amount', models.FloatField()),
            ],
        ),
    ]
