# Generated by Django 2.2.5 on 2020-04-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment',
            new_name='payments',
        ),
    ]
