# Generated by Django 2.2.5 on 2019-11-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='can_pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_username', models.CharField(max_length=100)),
                ('can_name', models.CharField(max_length=100)),
                ('can_house', models.CharField(max_length=100)),
                ('can_place', models.CharField(max_length=100)),
                ('can_pincode', models.IntegerField()),
                ('can_dob', models.DateField()),
                ('can_gender', models.CharField(max_length=50)),
                ('can_email', models.CharField(max_length=250)),
                ('can_mob', models.IntegerField()),
                ('can_dt', models.CharField(max_length=100)),
                ('can_state', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('sc_board', models.CharField(max_length=100)),
                ('sc_percent', models.IntegerField()),
                ('sc_yop', models.IntegerField()),
                ('hss', models.CharField(max_length=100)),
                ('hss_board', models.CharField(max_length=100)),
                ('hss_stream', models.CharField(max_length=100)),
                ('hss_yop', models.IntegerField()),
                ('hss_percent', models.IntegerField()),
                ('ug', models.CharField(max_length=100)),
                ('ug_uni', models.CharField(max_length=100)),
                ('ug_course', models.CharField(max_length=100)),
                ('ug_yop', models.IntegerField()),
                ('ug_percent', models.IntegerField()),
                ('pg', models.CharField(max_length=100)),
                ('pg_uni', models.CharField(max_length=100)),
                ('pg_course', models.CharField(max_length=100)),
                ('pg_yop', models.IntegerField()),
                ('pg_percent', models.IntegerField()),
            ],
        ),
    ]
