# Generated by Django 2.2.5 on 2019-11-16 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='can_pro',
            name='can_username',
        ),
    ]
