# Generated by Django 2.2.5 on 2019-11-16 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_remove_can_pro_can_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='can_pro',
            name='can_uname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
