# Generated by Django 2.2.5 on 2019-11-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_can_pro_can_uname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='can_pro',
            name='can_dob',
        ),
    ]
