# Generated by Django 2.2.5 on 2019-11-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_remove_can_pro_can_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobapply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('job_name', models.CharField(max_length=100)),
                ('com_uname', models.CharField(max_length=100)),
                ('can_uname', models.CharField(max_length=100)),
            ],
        ),
    ]
