# Generated by Django 2.2.5 on 2019-11-17 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_auto_20191117_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='com_uname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
