# Generated by Django 2.2.5 on 2019-11-17 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_jobapply_com_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='canname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
