# Generated by Django 2.2.5 on 2020-02-12 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_auto_20200210_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='apply_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
