# Generated by Django 2.2.5 on 2020-02-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_jobapply_apply_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('com_uname', models.CharField(max_length=100)),
                ('can_uname', models.CharField(max_length=100)),
            ],
        ),
    ]
