# Generated by Django 2.2.5 on 2020-02-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_shortlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can_pro',
            name='hss_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='can_pro',
            name='pg_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='can_pro',
            name='sc_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='can_pro',
            name='ug_percent',
            field=models.FloatField(),
        ),
    ]
