# Generated by Django 2.2.5 on 2020-02-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0014_jobapply_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='short',
            field=models.CharField(max_length=3),
        ),
    ]
