# Generated by Django 2.2.5 on 2020-02-17 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_auto_20200217_0944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shortlist',
        ),
    ]
