# Generated by Django 2.2.5 on 2020-02-18 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0016_delete_shortlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='short_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
