# Generated by Django 2.2.5 on 2020-03-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0018_jobapply_intw_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='call',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
