# Generated by Django 2.2.5 on 2020-03-09 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0019_jobapply_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='call_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
