# Generated by Django 2.2.5 on 2020-03-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0020_jobapply_call_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='intw_desc',
            field=models.TextField(),
        ),
    ]
