# Generated by Django 2.2.5 on 2020-03-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0021_auto_20200309_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='short_per',
            field=models.FloatField(default=1.1),
            preserve_default=False,
        ),
    ]
