# Generated by Django 2.2.5 on 2020-03-14 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0022_jobapply_short_per'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapply',
            name='short_per',
        ),
    ]
