# Generated by Django 2.2.5 on 2020-03-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0023_remove_jobapply_short_per'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='noti_all',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
