# Generated by Django 2.2.5 on 2020-03-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0024_jobapply_noti_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapply',
            name='noti_all',
        ),
    ]
