# Generated by Django 2.2.5 on 2020-03-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0025_remove_jobapply_noti_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='can_pro',
            name='skills',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
