# Generated by Django 2.2.5 on 2020-03-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0026_can_pro_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can_pro',
            name='can_pincode',
            field=models.IntegerField(blank=True),
        ),
    ]
