# Generated by Django 2.2.5 on 2020-03-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0027_auto_20200318_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can_pro',
            name='can_pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
