# Generated by Django 2.2.5 on 2020-03-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0028_auto_20200318_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can_pro',
            name='can_mob',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='can_pro',
            name='hss_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='can_pro',
            name='hss_yop',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='can_pro',
            name='pg_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='can_pro',
            name='pg_yop',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='can_pro',
            name='sc_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='can_pro',
            name='sc_yop',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='can_pro',
            name='ug_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='can_pro',
            name='ug_yop',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
