# Generated by Django 2.2.5 on 2020-03-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0029_auto_20200318_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='can_pro',
            name='skill1',
        ),
        migrations.RemoveField(
            model_name='can_pro',
            name='skill2',
        ),
        migrations.RemoveField(
            model_name='can_pro',
            name='skill3',
        ),
    ]
