# Generated by Django 2.2.5 on 2020-03-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0032_auto_20200321_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='can_pro',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
