# Generated by Django 2.2.5 on 2020-03-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0033_can_pro_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='can_pro',
            name='resume',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
