# Generated by Django 2.2.5 on 2020-03-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0034_can_pro_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can_pro',
            name='resume',
            field=models.FileField(upload_to='media/'),
        ),
    ]
