# Generated by Django 2.2.5 on 2020-04-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0035_auto_20200327_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='selected',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
