# Generated by Django 2.2.5 on 2020-04-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0036_jobapply_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can_pro',
            name='can_mob',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
