# Generated by Django 2.2.5 on 2020-04-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0038_auto_20200406_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='can_pro',
            name='img',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
