# Generated by Django 2.2.5 on 2019-11-09 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='com_pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=250)),
                ('com_desc', models.TextField()),
                ('com_place', models.CharField(max_length=250)),
                ('com_pincode', models.IntegerField()),
                ('com_dt', models.CharField(max_length=50)),
                ('com_state', models.CharField(max_length=50)),
                ('com_country', models.CharField(max_length=50)),
                ('com_mob', models.IntegerField()),
                ('com_email', models.CharField(max_length=250)),
                ('can_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
