# Generated by Django 2.2.5 on 2019-11-09 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='com_pro',
            old_name='can_id',
            new_name='username',
        ),
    ]
