# Generated by Django 2.2.5 on 2019-11-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20191109_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='com_pro',
            old_name='username',
            new_name='com_username',
        ),
    ]
