# Generated by Django 2.2.5 on 2019-11-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20191109_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com_pro',
            name='com_username',
            field=models.CharField(max_length=100),
        ),
    ]
