# Generated by Django 2.2.5 on 2019-11-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20191109_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='com_pro',
            old_name='com_country',
            new_name='comcountry',
        ),
        migrations.RenameField(
            model_name='com_pro',
            old_name='com_desc',
            new_name='comdesc',
        ),
        migrations.RenameField(
            model_name='com_pro',
            old_name='com_dt',
            new_name='comdt',
        ),
        migrations.RenameField(
            model_name='com_pro',
            old_name='com_email',
            new_name='comemail',
        ),
        migrations.RenameField(
            model_name='com_pro',
            old_name='com_mob',
            new_name='commob',
        ),
        migrations.RenameField(
            model_name='com_pro',
            old_name='com_name',
            new_name='comname',
        ),
        migrations.RenameField(
            model_name='com_pro',
            old_name='com_pincode',
            new_name='compincode',
        ),
        migrations.RenameField(
            model_name='com_pro',
            old_name='com_place',
            new_name='complace',
        ),
        migrations.RenameField(
            model_name='com_pro',
            old_name='com_state',
            new_name='comstate',
        ),
        migrations.RenameField(
            model_name='com_pro',
            old_name='com_username',
            new_name='comusername',
        ),
    ]
