# Generated by Django 2.2.5 on 2019-11-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_com_pro_comid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='com_pro',
            old_name='comcountry',
            new_name='com_country',
        ),
        migrations.RenameField(
            model_name='com_pro',
            old_name='comdesc',
            new_name='com_desc',
        ),
        migrations.RenameField(
            model_name='com_pro',
            old_name='comdt',
            new_name='com_dt',
        ),
        migrations.RenameField(
            model_name='com_pro',
            old_name='comemail',
            new_name='com_email',
        ),
        migrations.RenameField(
            model_name='com_pro',
            old_name='commob',
            new_name='com_mob',
        ),
        migrations.RenameField(
            model_name='com_pro',
            old_name='comname',
            new_name='com_name',
        ),
        migrations.RenameField(
            model_name='com_pro',
            old_name='compincode',
            new_name='com_pincode',
        ),
        migrations.RenameField(
            model_name='com_pro',
            old_name='complace',
            new_name='com_place',
        ),
        migrations.RenameField(
            model_name='com_pro',
            old_name='comstate',
            new_name='com_state',
        ),
        migrations.RemoveField(
            model_name='com_pro',
            name='comid',
        ),
        migrations.AddField(
            model_name='com_pro',
            name='com_username',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
