# Generated by Django 2.2.5 on 2019-11-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20191109_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_username', models.CharField(max_length=250)),
                ('job_name', models.CharField(max_length=250)),
                ('job_desc', models.TextField()),
                ('job_place', models.CharField(max_length=250)),
                ('job_pin', models.IntegerField()),
                ('job_dt', models.CharField(max_length=50)),
                ('job_st', models.CharField(max_length=50)),
                ('job_email', models.CharField(max_length=250)),
                ('com_phn', models.IntegerField()),
                ('com_con', models.CharField(max_length=50)),
            ],
        ),
    ]
