# Generated by Django 2.2.5 on 2019-11-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_jobpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='com_con',
            new_name='job_con',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='com_phn',
            new_name='job_phn',
        ),
    ]
