# Generated by Django 2.2.5 on 2019-11-10 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20191110_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='com_username',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_com',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.com_pro'),
            preserve_default=False,
        ),
    ]
