# Generated by Django 2.2.5 on 2019-11-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20191110_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='job_com',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='com_username',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
