# Generated by Django 2.2.5 on 2019-11-16 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20191110_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='com_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.com_pro'),
        ),
    ]
