# Generated by Django 2.2.5 on 2019-11-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20191116_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='com_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
