# Generated by Django 2.2.5 on 2019-11-16 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_jobpost_com_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='com_name',
        ),
    ]
