# Generated by Django 2.2.5 on 2019-11-16 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_remove_jobpost_com_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='com_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
