# Generated by Django 2.2.5 on 2019-11-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_jobpost_com_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_username', models.CharField(max_length=100)),
                ('com_name', models.CharField(max_length=100)),
                ('can_uname', models.CharField(max_length=100)),
            ],
        ),
    ]
