# Generated by Django 2.2.5 on 2019-11-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='job_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
