# Generated by Django 2.2.5 on 2019-11-18 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_interview_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='job_id',
        ),
        migrations.AddField(
            model_name='interview',
            name='in_desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interview',
            name='job_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
