# Generated by Django 2.2.5 on 2020-02-04 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_auto_20191118_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_qua',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
