# Generated by Django 2.2.5 on 2020-02-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_jobpost_job_qua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_qua',
            field=models.CharField(max_length=250),
        ),
    ]
