# Generated by Django 2.2.5 on 2020-02-10 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_auto_20200204_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='shrt_skill1',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='shrt_skill2',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='shrt_skill3',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
