# Generated by Django 2.2.5 on 2020-02-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_auto_20200210_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='shrtp_pg',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='shrtp_ten',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='shrtp_tlw',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='shrtp_ug',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
