# Generated by Django 2.2.5 on 2020-02-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_auto_20200210_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='shrtp_pg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='shrtp_ten',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='shrtp_tlw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='shrtp_ug',
            field=models.FloatField(),
        ),
    ]
