# Generated by Django 2.2.5 on 2020-02-11 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_auto_20200210_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='shrtp_pg',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='shrtp_ten',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='shrtp_tlw',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='shrtp_ug',
        ),
    ]
