# Generated by Django 2.2.5 on 2020-02-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_auto_20200211_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='shrtp_ten',
            field=models.FloatField(default=9.0),
            preserve_default=False,
        ),
    ]
