# Generated by Django 2.2.5 on 2020-02-12 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_jobpost_shrt_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='shrt_date',
            new_name='last_date',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='post_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
