# Generated by Django 2.2.5 on 2020-02-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_auto_20200212_2051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='qualification',
        ),
    ]
