# Generated by Django 2.2.5 on 2020-02-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_delete_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
