# Generated by Django 2.2.5 on 2020-03-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_interview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='shrt_skills',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
