# Generated by Django 2.2.5 on 2020-03-21 03:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0035_auto_20200318_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('com_username', models.CharField(max_length=100)),
                ('can_uname', models.CharField(max_length=100)),
                ('in_desc', models.CharField(max_length=100)),
                ('call', models.CharField(max_length=10)),
                ('call_date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='status',
            new_name='job_id',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='com_name',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='job_name',
        ),
        migrations.AddField(
            model_name='interview',
            name='call',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interview',
            name='call_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
