# Generated by Django 2.2.5 on 2020-03-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0036_auto_20200321_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
