# Generated by Django 2.2.5 on 2020-03-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0037_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='com_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='job_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
