# Generated by Django 2.2.5 on 2020-03-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0038_auto_20200321_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='com_pro',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
