# Generated by Django 2.2.5 on 2020-04-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0039_com_pro_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com_pro',
            name='com_mob',
            field=models.BigIntegerField(),
        ),
    ]
