# Generated by Django 2.2.5 on 2020-04-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0040_auto_20200405_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com_pro',
            name='com_pincode',
            field=models.BigIntegerField(),
        ),
    ]
