# Generated by Django 2.2.5 on 2020-04-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0041_auto_20200405_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_phn',
            field=models.BigIntegerField(),
        ),
    ]
