# Generated by Django 2.2.5 on 2020-04-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0042_auto_20200405_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='com_name',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='job_name',
        ),
    ]
