# Generated by Django 2.2.5 on 2020-04-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0043_auto_20200405_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='com_name',
        ),
    ]
