# Generated by Django 2.2.5 on 2020-04-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0044_remove_jobpost_com_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
